//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:14:47 PM CET 
//


package org.accapto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.accapto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _App_QNAME = new QName("org.accapto", "app");
    private final static QName _ScreenTypeAction_QNAME = new QName("org.accapto", "action");
    private final static QName _ScreenTypeTransition_QNAME = new QName("org.accapto", "transition");
    private final static QName _ScreenTypeInput_QNAME = new QName("org.accapto", "input");
    private final static QName _ScreenTypeOutput_QNAME = new QName("org.accapto", "output");
    private final static QName _ScreenTypeSubscreen_QNAME = new QName("org.accapto", "subscreen");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.accapto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppType }
     * 
     */
    public AppType createAppType() {
        return new AppType();
    }

    /**
     * Create an instance of {@link ScreenType }
     * 
     */
    public ScreenType createScreenType() {
        return new ScreenType();
    }

    /**
     * Create an instance of {@link InputType }
     * 
     */
    public InputType createInputType() {
        return new InputType();
    }

    /**
     * Create an instance of {@link OutputType }
     * 
     */
    public OutputType createOutputType() {
        return new OutputType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link TransitionType }
     * 
     */
    public TransitionType createTransitionType() {
        return new TransitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AppType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.accapto", name = "app")
    public JAXBElement<AppType> createApp(AppType value) {
        return new JAXBElement<AppType>(_App_QNAME, AppType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.accapto", name = "action", scope = ScreenType.class)
    public JAXBElement<ActionType> createScreenTypeAction(ActionType value) {
        return new JAXBElement<ActionType>(_ScreenTypeAction_QNAME, ActionType.class, ScreenType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.accapto", name = "transition", scope = ScreenType.class)
    public JAXBElement<TransitionType> createScreenTypeTransition(TransitionType value) {
        return new JAXBElement<TransitionType>(_ScreenTypeTransition_QNAME, TransitionType.class, ScreenType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.accapto", name = "input", scope = ScreenType.class)
    public JAXBElement<InputType> createScreenTypeInput(InputType value) {
        return new JAXBElement<InputType>(_ScreenTypeInput_QNAME, InputType.class, ScreenType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.accapto", name = "output", scope = ScreenType.class)
    public JAXBElement<OutputType> createScreenTypeOutput(OutputType value) {
        return new JAXBElement<OutputType>(_ScreenTypeOutput_QNAME, OutputType.class, ScreenType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScreenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.accapto", name = "subscreen", scope = ScreenType.class)
    public JAXBElement<ScreenType> createScreenTypeSubscreen(ScreenType value) {
        return new JAXBElement<ScreenType>(_ScreenTypeSubscreen_QNAME, ScreenType.class, ScreenType.class, value);
    }

}
